// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBItcD8-aUN-8yYYU57yR5Xxzf6cYlwOcc',
    appId: '1:691154773831:web:61c231505117c8edf70e62',
    messagingSenderId: '691154773831',
    projectId: 'gowtham-portfolio-91637',
    authDomain: 'gowtham-portfolio-91637.firebaseapp.com',
    storageBucket: 'gowtham-portfolio-91637.firebasestorage.app',
    measurementId: 'G-QVG9EKSSCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnuwaaVS61vdpzQqymvlcLdOf3qqWOiGA',
    appId: '1:691154773831:android:b92a50d802e7bb56f70e62',
    messagingSenderId: '691154773831',
    projectId: 'gowtham-portfolio-91637',
    storageBucket: 'gowtham-portfolio-91637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3v3z0vweUUP8hvMRPo6IF8aIFQtKc2Os',
    appId: '1:691154773831:ios:10a4b080196c1402f70e62',
    messagingSenderId: '691154773831',
    projectId: 'gowtham-portfolio-91637',
    storageBucket: 'gowtham-portfolio-91637.firebasestorage.app',
    iosBundleId: 'com.example.gowthamPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3v3z0vweUUP8hvMRPo6IF8aIFQtKc2Os',
    appId: '1:691154773831:ios:10a4b080196c1402f70e62',
    messagingSenderId: '691154773831',
    projectId: 'gowtham-portfolio-91637',
    storageBucket: 'gowtham-portfolio-91637.firebasestorage.app',
    iosBundleId: 'com.example.gowthamPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBItcD8-aUN-8yYYU57yR5Xxzf6cYlwOcc',
    appId: '1:691154773831:web:b2e4982155777a0bf70e62',
    messagingSenderId: '691154773831',
    projectId: 'gowtham-portfolio-91637',
    authDomain: 'gowtham-portfolio-91637.firebaseapp.com',
    storageBucket: 'gowtham-portfolio-91637.firebasestorage.app',
    measurementId: 'G-VCBPJ8ZJYF',
  );
}
